# Generated by Django 6.0.1 on 2026-02-03 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilha', '0001_initial'),
        ('usuarios', '0002_usuario_monitor_responsavel_alter_usuario_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='step',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mundo',
            name='aluno',
            field=models.ForeignKey(blank=True, help_text='Aluno dono desta trilha. Null = Trilha Base (template)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mundos_personalizados', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='mundo',
            name='objetivo',
            field=models.TextField(blank=True, help_text='Objetivo do mundo'),
        ),
        migrations.AddField(
            model_name='step',
            name='config_formulario',
            field=models.JSONField(blank=True, help_text='Perguntas do formulário: [{pergunta: str, obrigatoria: bool}]', null=True),
        ),
        migrations.AlterField(
            model_name='mundo',
            name='numero',
            field=models.IntegerField(help_text='Número do mundo (1-6)'),
        ),
        migrations.AlterUniqueTogether(
            name='mundo',
            unique_together={('aluno', 'numero')},
        ),
    ]
