# Generated by Django 6.0.1 on 2026-02-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilha', '0002_alter_step_unique_together_mundo_aluno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='pos_x',
            field=models.IntegerField(default=0, help_text='Posição Horizontal (%)'),
        ),
        migrations.AddField(
            model_name='step',
            name='pos_y',
            field=models.IntegerField(default=0, help_text='Posição Vertical (%)'),
        ),
    ]
