# Generated by Django 5.2.11 on 2026-03-03 23:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_usuario_monitor_responsavel_alter_usuario_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total_negociado', models.DecimalField(decimal_places=2, help_text='Valor total negociado no contrato', max_digits=10)),
                ('data_assinatura', models.DateField(default=django.utils.timezone.now)),
                ('observacoes_gerais', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('CANCELADO', 'Cancelado')], default='ATIVO', max_length=20)),
                ('aluno', models.OneToOneField(help_text='Aluno vinculado a este contrato', limit_choices_to={'role': 'ALUNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Número da parcela (1, 2, 3...)')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, help_text='Preencha quando a parcela for paga', null=True)),
                ('link_pagamento_ou_pix', models.CharField(blank=True, help_text='Link de cobrança ou chave PIX', max_length=500)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes_pagamento/')),
                ('observacoes', models.TextField(blank=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='financeiro.contrato')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'ordering': ['data_vencimento', 'numero'],
                'unique_together': {('contrato', 'numero')},
            },
        ),
    ]
