# Generated by Django 5.2.11 on 2026-03-06 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
        ('usuarios', '0003_usuario_pode_aprovar_financeiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='asaas_customer_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='contrato',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='comprovante_entrada',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes_entrada/'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='contrato_assinado',
            field=models.FileField(blank=True, null=True, upload_to='contratos_assinados/'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_criados', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='parcela',
            name='asaas_invoice_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='parcela',
            name='asaas_payment_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='parcela',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parcela',
            name='origem',
            field=models.CharField(choices=[('CADASTRO', 'Cadastro'), ('RENEGOCIACAO', 'Renegociacao')], default='CADASTRO', max_length=20),
        ),
        migrations.AddField(
            model_name='parcela',
            name='sincronizada_asaas_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcela',
            name='tipo_parcela',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('RECORRENTE', 'Recorrente')], default='RECORRENTE', max_length=20),
        ),
    ]
