# Generated by Django 5.2.11 on 2026-03-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_contrato_asaas_customer_id_contrato_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='metodo_pagamento',
            field=models.CharField(choices=[('PIX', 'Pix'), ('BOLETO', 'Boleto'), ('CARTAO', 'Cartao'), ('TRANSFERENCIA', 'Transferencia'), ('DINHEIRO', 'Dinheiro')], default='PIX', max_length=20),
        ),
    ]
