# Generated by Django 5.2.11 on 2026-03-09 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_contrato_metodo_pagamento'),
        ('usuarios', '0003_usuario_pode_aprovar_financeiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='ja_renegociada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parcela',
            name='parcela_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelas_derivadas', to='financeiro.parcela'),
        ),
        migrations.CreateModel(
            name='PropostaRenegociacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_renegociacao', models.CharField(choices=[('ADIAR', 'Adiar'), ('QUEBRAR', 'Quebrar')], max_length=20)),
                ('dados_fatiamento', models.JSONField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas_renegociacao', to='financeiro.contrato')),
                ('criada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propostas_renegociacao_criadas', to='usuarios.usuario')),
                ('parcela_alvo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas_renegociacao', to='financeiro.parcela')),
            ],
            options={
                'verbose_name': 'Proposta de renegociacao',
                'verbose_name_plural': 'Propostas de renegociacao',
                'ordering': ['-criada_em'],
            },
        ),
    ]
