# Generated by Django 6.0.1 on 2026-02-03 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='monitor_responsavel',
            field=models.ForeignKey(blank=True, help_text='Monitor responsável pelo aluno (apenas para alunos)', limit_choices_to={'role': 'MONITOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos_responsaveis', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('MONITOR', 'Monitor'), ('ALUNO', 'Aluno'), ('COMERCIAL', 'Comercial')], default='ALUNO', max_length=20),
        ),
    ]
