# Generated by Django 5.2.11 on 2026-03-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_monitor_responsavel_alter_usuario_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pode_aprovar_financeiro',
            field=models.BooleanField(default=False),
        ),
    ]
