# Generated by Django 5.2.11 on 2026-03-06 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financeiro', '0002_contrato_asaas_customer_id_contrato_atualizado_em_and_more'),
        ('usuarios', '0003_usuario_pode_aprovar_financeiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('EMAIL', 'E-mail'), ('WHATSAPP', 'WhatsApp')], max_length=20)),
                ('destinatario', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('status', models.CharField(choices=[('PREPARADO', 'Preparado'), ('ENVIADO', 'Enviado'), ('ERRO', 'Erro')], default='PREPARADO', max_length=20)),
                ('erro', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(limit_choices_to={'role': 'ALUNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='envios_onboarding', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Envio de onboarding',
                'verbose_name_plural': 'Envios de onboarding',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='NotificacaoInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ONBOARDING', 'Onboarding'), ('PROPOSTA_FINANCEIRA', 'Proposta Financeira'), ('SISTEMA', 'Sistema')], default='SISTEMA', max_length=30)),
                ('titulo', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('url_destino', models.CharField(blank=True, max_length=255)),
                ('lida', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(blank=True, limit_choices_to={'role': 'ALUNO'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_relacionadas', to='usuarios.usuario')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_recebidas', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Notificacao interna',
                'verbose_name_plural': 'Notificacoes internas',
                'ordering': ['lida', '-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='PerfilEmpresarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=200)),
                ('telefone_empresa', models.CharField(blank=True, max_length=20)),
                ('cnpj', models.CharField(blank=True, max_length=18)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('nicho', models.CharField(choices=[('RESTAURANTE', 'Restaurante'), ('CAFE', 'Cafe'), ('LANCHONETE', 'Lanchonete'), ('DELIVERY', 'Delivery'), ('PADARIA', 'Padaria'), ('OUTRO', 'Outro')], default='OUTRO', max_length=30)),
                ('nome_representante', models.CharField(blank=True, max_length=200)),
                ('cpf_representante', models.CharField(blank=True, max_length=14)),
                ('dificuldades', models.JSONField(blank=True, default=list)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.OneToOneField(limit_choices_to={'role': 'ALUNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_empresarial', to='usuarios.usuario')),
                ('monitor_responsavel_snapshot', models.ForeignKey(blank=True, limit_choices_to={'role': 'MONITOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfis_empresariais_snapshot', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Perfil empresarial',
                'verbose_name_plural': 'Perfis empresariais',
            },
        ),
        migrations.CreateModel(
            name='PropostaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada')], default='PENDENTE', max_length=20)),
                ('motivo', models.TextField()),
                ('observacao_monitor', models.TextField(blank=True)),
                ('observacao_admin', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('aprovada_em', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(limit_choices_to={'role': 'ALUNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='propostas_financeiras', to='usuarios.usuario')),
                ('aprovada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propostas_financeiras_aprovadas', to='usuarios.usuario')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas_financeiras', to='financeiro.contrato')),
                ('criada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas_financeiras_criadas', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Proposta financeira',
                'verbose_name_plural': 'Propostas financeiras',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='PropostaFinanceiraParcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('observacoes', models.TextField(blank=True)),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas_propostas', to='comercial.propostafinanceira')),
            ],
            options={
                'verbose_name': 'Parcela proposta',
                'verbose_name_plural': 'Parcelas propostas',
                'ordering': ['numero'],
                'unique_together': {('proposta', 'numero')},
            },
        ),
    ]
